language: node_js
node_js:
  - 0.8
script: "npm run-script coveralls"
env:
  - secure: "F91QQC1hxCyFyvQ8g7ASwFYwsI1Q+nF0GJIl1vEcB12qtMN8/Zw8EJoJ9px5\nmoAl6c9qN/HnCByb0azsALg08ofzZMfHKvJz4rYnDVAWhC/N174QDgmZ4B5Y\nlVfZhcBmPJDv8qXMXV2TgJPXpI0bouDjuj0xX0ca/MDBrN/0HDc="
